services:
  web:
    build: .
    container_name: panchita_web
    command: sh -c "mkdir -p /app/media/productos /app/backups /app/staticfiles && chmod -R 755 /app/media /app/backups /app/staticfiles && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=panchita_db
      - DB_USER=panchita_user
      - DB_PASSWORD=panchita_pass
      - DB_PORT=3306
      - DJANGO_SECRET_KEY=dev_secret_key_123
      - PYTHONUNBUFFERED=1
    networks:
      panchita_network:
        ipv4_address: 192.168.100.10
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: panchita_db_container
    environment:
      MYSQL_DATABASE: panchita_db
      MYSQL_USER: panchita_user
      MYSQL_PASSWORD: panchita_pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data_django:/var/lib/mysql
    ports:
      - "3309:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      panchita_network:
        ipv4_address: 192.168.100.20
    restart: unless-stopped

networks:
  panchita_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1

volumes:
  mysql_data_django:
  static_volume:
  media_volume:
